fixtures:
  symlinks:
    activemq: '#{source_dir}'
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    java:
      repo: "puppetlabs/java"
      ref: "1.5.0"
#    concat: "puppetlabs/concat"
#    archive: "puppet-archive"
#    selinux: "jfryman/selinux"
#    awscli: "jdowning/awscli"
#    epel: "stahnma/epel"
#    nginx: "jfryman/nginx"
#    staging: "nanliu/staging"
#    apt: "puppetlabs/apt"
#    shellvar: "herculesteam/augeasproviders_shellvar"
#    auges_core: "herculesteam/augeasproviders_core"
#    tomcat:
#      repo: "puppetlabs/tomcat"
#      ref: "1.5.0"
#
#    wget:
#     repo: "maestrodev/wget"
#     ref: "1.7.3"